from fastapi import APIRouter
from fastapi.responses import StreamingResponse
import io
import pandas as pd

router = APIRouter()

@router.get("/csv")
def export_csv(buyer_gstin: str = "07AAGFF2194N1Z1"):
    # Mock data for report
    data = {
        "Vendor_GSTIN": ["09AAJFF1122K1Z9", "27AADCB2230M1Z1"],
        "Invoice_Number": ["INV-001", "INV-002"],
        "Mismatch_Status": ["Matched", "Mismatched"],
        "ITC_At_Risk": [0, 45000]
    }
    df = pd.DataFrame(data)
    
    stream = io.StringIO()
    df.to_csv(stream, index=False)
    
    response = StreamingResponse(iter([stream.getvalue()]), media_type="text/csv")
    response.headers["Content-Disposition"] = "attachment; filename=reconciliation_report.csv"
    return response

@router.get("/ai-compliance")
def get_ai_report():
    # Simulated long-form AI report
    report = """
    # GST Compliance Report (Generated by GraphGST AI)
    
    ## Executive Summary
    Your organization has successfully reconciled 1,100 invoices this month. However, there are 145 invoices with discrepancies leading to ₹2,40,500 of Input Tax Credit currently at risk.
    
    ## Top Risks
    - **Vendor A** has the highest risk score (85) with 12 missing invoices.
    - **Vendor B** has filed invoices with significant value mismatches (₹45,000 variance).
    
    ## AI Recommendations
    1. **Immediate Action**: Follow up with Vendor A to file their GSTR-1 before the 11th.
    2. **Process Update**: Implement stricter payment releases for vendors falling below a 60% compliance score.
    """
    return {"report": report}
